version: '3.5'

services:
  igdbdb:
    image: mongo
    ports:
      - "27017:27017"
  igdbweb:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - igdbdb
