# Generated by Django 2.0.7 on 2018-08-01 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome completo do usuário', max_length=150, verbose_name='Nome')),
                ('is_staff', models.BooleanField(default=False, help_text='Verify if the user is a staff.', verbose_name='Is Staff?')),
                ('is_student', models.BooleanField(default=False, help_text='Verificar se o usuário é um aluno', verbose_name='Is Student?')),
                ('is_secretary', models.BooleanField(default=False, help_text='Verificar se o usuário é um Secretaria Acadêmica', verbose_name='Is Secretary?')),
                ('is_library', models.BooleanField(default=False, help_text='Verificar se o usuário é um Bibliotecário', verbose_name='Is Librarian?')),
                ('is_finance', models.BooleanField(default=False, help_text='Verificar se o usuário é do Financeiro', verbose_name='Is Finance?')),
                ('is_coordination', models.BooleanField(default=False, help_text='Verificar se o usuário é da Coordenação', verbose_name='Is Coordination')),
                ('is_napes', models.BooleanField(default=False, help_text='Verificar se o usuário é NAPES', verbose_name='Is NAPES?')),
                ('is_director', models.BooleanField(default=False, help_text='Verificar se o usuário é Diretor Acadêmico', verbose_name='Is Director?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date that the user is created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date that the user is updated.', verbose_name='Updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
