# Generated by Django 2.0.7 on 2018-08-02 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(help_text='Parecer de certo funcionário', max_length=300, verbose_name='Parecer')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data que o parecer foi criado', verbose_name='Data')),
                ('feedbacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parecer',
                'verbose_name_plural': 'Pareceres',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Solicitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(help_text='Número do processo', max_length=15, unique=True, verbose_name='Processo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data que a solicitação foi criada', verbose_name='Data')),
                ('student_semester', models.CharField(help_text='Período/Turma do Estudante', max_length=15, verbose_name='Período/Turma')),
                ('student_academic_situation', models.CharField(help_text='Situação Acadêmica do Estudante', max_length=30, verbose_name='Situação')),
                ('solicitation', models.CharField(help_text='Solicitação', max_length=30, verbose_name='Solicitação')),
                ('reason', models.CharField(help_text='Justificativa da solicitação', max_length=300, verbose_name='Justificativa')),
                ('status', models.CharField(help_text='Status da Solicitação', max_length=30, verbose_name='Status')),
                ('feedbacks', models.ManyToManyField(to='accounts.Feedback')),
                ('student', models.ForeignKey(help_text='Estudante requerinte', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requerimento',
                'verbose_name_plural': 'Requerimentos',
                'ordering': ('created_at',),
            },
        ),
    ]
