# Generated by Django 2.0.7 on 2018-08-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_feedback_solicitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='solicitations',
            field=models.ManyToManyField(to='accounts.Solicitation'),
        ),
    ]
