# Generated by Django 2.0.7 on 2018-08-03 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_solicitations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Usuario')),
                ('email', models.CharField(help_text='E-mail do Aluno', max_length=35, verbose_name='E-mail')),
                ('course', models.CharField(help_text='Curso do Aluno', max_length=30, verbose_name='Curso')),
                ('semester', models.CharField(help_text='Período que o aluno está cursando', max_length=10, verbose_name='Período')),
                ('code', models.CharField(help_text='Matrícula do Aluno', max_length=15, verbose_name='Matrícula')),
            ],
            options={
                'ordering': ('created_at',),
                'verbose_name_plural': 'Alunos',
                'verbose_name': 'Aluno',
            },
            bases=('accounts.usuario',),
        ),
    ]
