# Generated by Django 2.0.7 on 2018-08-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='usuario_ptr',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
