# Generated by Django 2.0.7 on 2018-08-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180803_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='feedbacks',
            field=models.ManyToManyField(blank=True, to='accounts.Feedback'),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='student_academic_situation',
            field=models.CharField(help_text='Situação Acadêmica do Estudante', max_length=50, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='solicitations',
            field=models.ManyToManyField(blank=True, to='accounts.Solicitation'),
        ),
    ]
