# Generated by Django 2.0.7 on 2018-08-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180806_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(help_text='Parecer de certo funcionário', max_length=500, verbose_name='Parecer'),
        ),
    ]
