# Generated by Django 2.0.7 on 2018-08-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180806_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='code',
            field=models.CharField(default='Matrícula não informada', help_text='Matrícula do Estudante', max_length=20, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='student_academic_situation',
            field=models.CharField(default='Situação acadêmica ainda não informada', help_text='Situação Acadêmica do Estudante', max_length=50, verbose_name='Situação'),
        ),
    ]
