# Generated by Django 2.0.7 on 2018-08-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180808_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='E-mail não informado', help_text='E-mail do usuário', max_length=50, verbose_name='E-mail'),
        ),
    ]
