# Generated by Django 2.0.7 on 2018-08-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.AddField(
            model_name='solicitation',
            name='email',
            field=models.CharField(default='E-mail não informado', help_text='E-mail do usuário', max_length=50, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='phone1',
            field=models.CharField(default='Telefone não informado', help_text='Telefone principal do Aluno', max_length=12, verbose_name='Telefone 1'),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='phone2',
            field=models.CharField(default='Telefone não informado', help_text='Telefone secundário do Aluno', max_length=12, verbose_name='Telefone 2'),
        ),
    ]
