# Generated by Django 2.0.7 on 2018-08-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180808_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Data que a solicitação foi criada', verbose_name='Data'),
        ),
    ]
