# Generated by Django 2.0.7 on 2018-08-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180809_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(default='Parecer não informado', help_text='Parecer de certo funcionário', max_length=500, verbose_name='Parecer'),
        ),
    ]
