# Generated by Django 2.0.7 on 2018-08-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180809_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_caa',
            field=models.BooleanField(default=False, help_text='Verificar se o usuário é da Central de Atendimento ao Aluno', verbose_name='Is CAA?'),
        ),
    ]
