# Generated by Django 2.0.7 on 2018-08-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_usuario_is_caa'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='document',
            field=models.FileField(default=False, upload_to='anexos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
