# Generated by Django 2.0.7 on 2018-08-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180810_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitation',
            name='attachment',
        ),
        migrations.AddField(
            model_name='solicitation',
            name='attachment_birth_marriage_certificate',
            field=models.FileField(default=False, help_text='Certidão de casamento/Nascimento Anexado pelo estudante', upload_to='anexos/%Y/%m/certidao-casamento-nascimento/', verbose_name='Certidão de casamento/Nascimento'),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='attachment_cpf',
            field=models.FileField(default=False, help_text='CPF Anexado pelo estudante', upload_to='anexos/%Y/%m/CPF/', verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='attachment_highschool_certificate',
            field=models.FileField(default=False, help_text='Certificado de Conclusão do Ensino Médio Anexado pelo estudante', upload_to='anexos/%Y/%m/school-certificate/', verbose_name='Certificado de Conclusão do Ensino Médio'),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='attachment_proof_electoral_discharge',
            field=models.FileField(default=False, help_text='Comprovante de Quitação Eleitoral Anexado pelo estudante', upload_to='anexos/%Y/%m/comprovante-quitacao-eleitoral/', verbose_name='Comprovante de Quitação Eleitoral'),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='attachment_reservist',
            field=models.FileField(default=False, help_text='Título de Reservista Anexado pelo estudante', upload_to='anexos/%Y/%m/reservista/', verbose_name='Título de Reservista'),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='attachment_rg',
            field=models.FileField(default=False, help_text='RG Anexado pelo estudante', upload_to='anexos/%Y/%m/RG/', verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='attachment_school_conclusion_historic',
            field=models.FileField(default=False, help_text='Histórico de Conclusão do Ensino Médio Anexado pelo estudante', upload_to='anexos/%Y/%m/school-historic/', verbose_name='Histórico de Conclusão do Ensino Médio'),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='attachment_voters_title',
            field=models.FileField(default=False, help_text='Título de Eleitor Anexado pelo estudante', upload_to='anexos/%Y/%m/Titulo-de-Eleitor/', verbose_name='Título de Eleitor'),
        ),
    ]
